Page Title: Katespade/PayPalPage

#Object Definitions     
====================================================================================
txtbx_email									css						#login_emaildiv #email
txtbx_password								css						#login_passworddiv #password
btn_logIn									css						button#btnLogin
btn_next									css						button#btnNext
btn_continue								css						#confirmButtonTop
iframe                                      css                     [name="injectedUl"]